"""
All 24 roadmap templates for BA Compass: 8 engagement types × 3 scale tiers.
Source: F2_Product_Definition_v1.0.docx, Section 8.
Each template is an ordered list of module names that MUST exactly match
the 'name' field in modules.py.
"""

TEMPLATES = [
    # ─── Process Improvement ─────────────────────────────────────────────────
    {
        "engagement_type": "Process Improvement",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Current State Assessment",
            "Stakeholder Interviews",
            "Root Cause Analysis",
            "Functional Requirements Documentation",
            "Future State Design",
            "Acceptance Criteria Definition",
        ],
    },
    {
        "engagement_type": "Process Improvement",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Stakeholder Interviews",
            "Root Cause Analysis",
            "Gap Analysis",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Future State Design",
            "Process Modeling — Future State",
            "Assumption & Constraint Documentation",
            "Acceptance Criteria Definition",
            "Requirements Sign-off & Approval",
        ],
    },
    {
        "engagement_type": "Process Improvement",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Problem Statement Definition",
            "Business Need Definition",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Gap Analysis",
            "Future State Design",
            "Process Modeling — Future State",
            "Change Strategy Definition",
            "Business Case Development",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Acceptance Criteria Definition",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── New System / Technology Implementation ───────────────────────────────
    {
        "engagement_type": "New System / Technology Implementation",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Interviews",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Acceptance Criteria Definition",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "New System / Technology Implementation",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Stakeholder Interviews",
            "Document Analysis",
            "Current State Assessment",
            "Assumption & Constraint Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Data Requirements Definition",
            "Business Rules Documentation",
            "Use Case Development",
            "User Story Writing",
            "Acceptance Criteria Definition",
            "Requirements Prioritization",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "New System / Technology Implementation",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Problem Statement Definition",
            "Business Need Definition",
            "Business Case Development",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Data Requirements Definition",
            "Business Rules Documentation",
            "Use Case Development",
            "User Story Writing",
            "Acceptance Criteria Definition",
            "Solution Prototyping & Wireframing",
            "Requirements Verification",
            "Requirements Validation",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "Change Strategy Definition",
            "UAT Planning & Support",
            "Solution Performance Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Data & Reporting ─────────────────────────────────────────────────────
    {
        "engagement_type": "Data & Reporting",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Interviews",
            "Data Requirements Definition",
            "Functional Requirements Documentation",
            "Acceptance Criteria Definition",
        ],
    },
    {
        "engagement_type": "Data & Reporting",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Register",
            "Stakeholder Interviews",
            "Document Analysis",
            "Current State Assessment",
            "Data Requirements Definition",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Business Rules Documentation",
            "Acceptance Criteria Definition",
            "Solution Prototyping & Wireframing",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "Data & Reporting",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Problem Statement Definition",
            "Business Need Definition",
            "Business Case Development",
            "Current State Assessment",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Data Requirements Definition",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Business Rules Documentation",
            "Process Modeling — Current State",
            "Future State Design",
            "Gap Analysis",
            "Solution Prototyping & Wireframing",
            "Requirements Verification",
            "Requirements Validation",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Acceptance Criteria Definition",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Regulatory & Compliance ──────────────────────────────────────────────
    {
        "engagement_type": "Regulatory & Compliance",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Document Analysis",
            "Assumption & Constraint Documentation",
            "Functional Requirements Documentation",
            "Acceptance Criteria Definition",
        ],
    },
    {
        "engagement_type": "Regulatory & Compliance",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Document Analysis",
            "Current State Assessment",
            "Gap Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Business Rules Documentation",
            "Future State Design",
            "Acceptance Criteria Definition",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "Regulatory & Compliance",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Problem Statement Definition",
            "Business Need Definition",
            "Business Case Development",
            "Document Analysis",
            "Current State Assessment",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Business Rules Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Gap Analysis",
            "Future State Design",
            "Process Modeling — Future State",
            "Change Strategy Definition",
            "Requirements Verification",
            "Requirements Validation",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Acceptance Criteria Definition",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
            "Solution Performance Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Organizational Change ────────────────────────────────────────────────
    {
        "engagement_type": "Organizational Change",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Interviews",
            "Current State Assessment",
            "Assumption & Constraint Documentation",
            "Functional Requirements Documentation",
            "Acceptance Criteria Definition",
        ],
    },
    {
        "engagement_type": "Organizational Change",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Stakeholder Interviews",
            "Current State Assessment",
            "Root Cause Analysis",
            "Gap Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Business Requirements Documentation",
            "Future State Design",
            "Change Strategy Definition",
            "RACI Matrix",
            "Acceptance Criteria Definition",
            "Requirements Sign-off & Approval",
        ],
    },
    {
        "engagement_type": "Organizational Change",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Problem Statement Definition",
            "Business Need Definition",
            "Business Case Development",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Survey & Questionnaire Design",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Gap Analysis",
            "Future State Design",
            "Process Modeling — Future State",
            "Change Strategy Definition",
            "RACI Matrix",
            "Performance Metrics Definition",
            "Requirements Prioritization",
            "Requirements Sign-off & Approval",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── New Product / Service Development ───────────────────────────────────
    {
        "engagement_type": "New Product / Service Development",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Interviews",
            "Business Need Definition",
            "User Story Writing",
            "Acceptance Criteria Definition",
            "Functional Requirements Documentation",
        ],
    },
    {
        "engagement_type": "New Product / Service Development",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Stakeholder Interviews",
            "Elicitation Planning",
            "Document Analysis",
            "Current State Assessment",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "User Story Writing",
            "Acceptance Criteria Definition",
            "Solution Prototyping & Wireframing",
            "Business Rules Documentation",
            "Requirements Prioritization",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "New Product / Service Development",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Problem Statement Definition",
            "Business Need Definition",
            "Business Case Development",
            "Benchmarking & Market Analysis",
            "Current State Assessment",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Survey & Questionnaire Design",
            "Elicitation Planning",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Data Requirements Definition",
            "Business Rules Documentation",
            "User Story Writing",
            "Use Case Development",
            "Acceptance Criteria Definition",
            "Solution Prototyping & Wireframing",
            "Requirements Verification",
            "Requirements Validation",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "Change Strategy Definition",
            "UAT Planning & Support",
            "Solution Performance Assessment",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Vendor Selection & Procurement ──────────────────────────────────────
    {
        "engagement_type": "Vendor Selection & Procurement",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Interviews",
            "Business Need Definition",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Assumption & Constraint Documentation",
        ],
    },
    {
        "engagement_type": "Vendor Selection & Procurement",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Interviews",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Business Rules Documentation",
            "Assumption & Constraint Documentation",
            "Risk Assessment",
            "Requirements Prioritization",
            "Requirements Sign-off & Approval",
        ],
    },
    {
        "engagement_type": "Vendor Selection & Procurement",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Problem Statement Definition",
            "Business Need Definition",
            "Business Case Development",
            "Current State Assessment",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Elicitation Results Documentation",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Business Rules Documentation",
            "Requirements Prioritization",
            "Requirements Verification",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "Solution Performance Assessment",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Strategic Initiative ─────────────────────────────────────────────────
    {
        "engagement_type": "Strategic Initiative",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Interviews",
            "Document Analysis",
            "Assumption & Constraint Documentation",
            "Business Case Development",
        ],
    },
    {
        "engagement_type": "Strategic Initiative",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Current State Assessment",
            "Root Cause Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Gap Analysis",
            "Future State Design",
            "Business Case Development",
            "Change Strategy Definition",
            "Requirements Sign-off & Approval",
        ],
    },
    {
        "engagement_type": "Strategic Initiative",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Performance Metrics Definition",
            "Problem Statement Definition",
            "Business Need Definition",
            "Business Case Development",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Survey & Questionnaire Design",
            "Benchmarking & Market Analysis",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Assumption & Constraint Documentation",
            "Gap Analysis",
            "Future State Design",
            "Process Modeling — Future State",
            "Change Strategy Definition",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Requirements Sign-off & Approval",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },
]
