"""
All 24 roadmap templates for BA Compass: 8 engagement types × 3 scale tiers.
Source: F2_Product_Definition_v1.0.docx, Section 8.
Each template is an ordered list of module names that MUST exactly match
the 'name' field in modules.py.

ENH-07 Sequencing Principles (applied to all templates):
  1. Assumptions & Constraints early — document knowns before eliciting unknowns
  2. Elicitation before analysis — conduct interviews/workshops before RCA/gap
  3. Current state before future state — understand before redesigning
  4. Requirements before acceptance criteria, sign-off last
"""

TEMPLATES = [
    # ─── Process Improvement ─────────────────────────────────────────────────
    # Sequencing rationale:
    #   Elicitation (Stakeholder Interviews) before Current State Assessment so
    #   the BA understands context before documenting the current process.
    #   Root Cause Analysis comes after understanding current state.
    #   Future State Design follows analysis. Requirements documented after design.
    #   Acceptance Criteria defined last, before any sign-off.
    {
        "engagement_type": "Process Improvement",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Interviews",
            "Current State Assessment",
            "Root Cause Analysis",
            "Future State Design",
            "Functional Requirements Documentation",
            "Acceptance Criteria Definition",
        ],
    },
    {
        "engagement_type": "Process Improvement",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Assumption & Constraint Documentation",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Stakeholder Interviews",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Root Cause Analysis",
            "Future State Design",
            "Process Modeling — Future State",
            "Gap Analysis",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Acceptance Criteria Definition",
            "Requirements Sign-off & Approval",
        ],
    },
    {
        "engagement_type": "Process Improvement",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Gap Analysis",
            "Future State Design",
            "Process Modeling — Future State",
            "Change Strategy Definition",
            "Business Case Development",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Acceptance Criteria Definition",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── New System / Technology Implementation ───────────────────────────────
    # Sequencing rationale:
    #   Elicitation (Stakeholder Interviews) before Current State Assessment.
    #   Assumptions & Constraints documented after stakeholder engagement so
    #   they reflect what the interviews confirmed.
    #   Functional and Non-Functional requirements before use cases/user stories.
    #   UAT Planning last — it requires complete requirements.
    {
        "engagement_type": "New System / Technology Implementation",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Interviews",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Acceptance Criteria Definition",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "New System / Technology Implementation",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Stakeholder Interviews",
            "Document Analysis",
            "Current State Assessment",
            "Assumption & Constraint Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Data Requirements Definition",
            "Business Rules Documentation",
            "Use Case Development",
            "User Story Writing",
            "Acceptance Criteria Definition",
            "Requirements Prioritization",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "New System / Technology Implementation",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Data Requirements Definition",
            "Business Rules Documentation",
            "Use Case Development",
            "User Story Writing",
            "Acceptance Criteria Definition",
            "Solution Prototyping & Wireframing",
            "Requirements Verification",
            "Requirements Validation",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "Change Strategy Definition",
            "UAT Planning & Support",
            "Solution Performance Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Data & Reporting ─────────────────────────────────────────────────────
    # Sequencing rationale:
    #   Elicitation before data requirements definition — understand business
    #   context before specifying data needs.
    #   Current State Assessment before future design.
    #   Prototyping (wireframing) after requirements, before acceptance criteria.
    {
        "engagement_type": "Data & Reporting",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Interviews",
            "Data Requirements Definition",
            "Functional Requirements Documentation",
            "Acceptance Criteria Definition",
        ],
    },
    {
        "engagement_type": "Data & Reporting",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Register",
            "Stakeholder Interviews",
            "Document Analysis",
            "Current State Assessment",
            "Assumption & Constraint Documentation",
            "Data Requirements Definition",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Business Rules Documentation",
            "Solution Prototyping & Wireframing",
            "Acceptance Criteria Definition",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "Data & Reporting",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Current State Assessment",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Data Requirements Definition",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Business Rules Documentation",
            "Process Modeling — Current State",
            "Future State Design",
            "Gap Analysis",
            "Solution Prototyping & Wireframing",
            "Requirements Verification",
            "Requirements Validation",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Acceptance Criteria Definition",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Regulatory & Compliance ──────────────────────────────────────────────
    # Sequencing rationale:
    #   Document Analysis before Current State Assessment — regulatory context
    #   must be established before assessing current state against it.
    #   Assumptions & Constraints early — compliance constraints are known upfront.
    #   Risk Assessment before requirements — regulatory risks shape requirements.
    #   Future State Design after gap is understood.
    {
        "engagement_type": "Regulatory & Compliance",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Document Analysis",
            "Assumption & Constraint Documentation",
            "Functional Requirements Documentation",
            "Acceptance Criteria Definition",
        ],
    },
    {
        "engagement_type": "Regulatory & Compliance",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Document Analysis",
            "Assumption & Constraint Documentation",
            "Current State Assessment",
            "Stakeholder Interviews",
            "Risk Assessment",
            "Gap Analysis",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Business Rules Documentation",
            "Future State Design",
            "Acceptance Criteria Definition",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "Regulatory & Compliance",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Document Analysis",
            "Current State Assessment",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Gap Analysis",
            "Business Rules Documentation",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Future State Design",
            "Process Modeling — Future State",
            "Change Strategy Definition",
            "Business Case Development",
            "Requirements Verification",
            "Requirements Validation",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Acceptance Criteria Definition",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
            "Solution Performance Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Organizational Change ────────────────────────────────────────────────
    # Sequencing rationale:
    #   Stakeholder elicitation early — org change is highly stakeholder-driven.
    #   Assumptions & Constraints after initial stakeholder engagement.
    #   Current State before Root Cause Analysis and Gap.
    #   Change Strategy and RACI after understanding current state and requirements.
    {
        "engagement_type": "Organizational Change",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Stakeholder Interviews",
            "Current State Assessment",
            "Assumption & Constraint Documentation",
            "Functional Requirements Documentation",
            "Acceptance Criteria Definition",
        ],
    },
    {
        "engagement_type": "Organizational Change",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Stakeholder Interviews",
            "Assumption & Constraint Documentation",
            "Current State Assessment",
            "Root Cause Analysis",
            "Risk Assessment",
            "Gap Analysis",
            "Business Requirements Documentation",
            "Future State Design",
            "Change Strategy Definition",
            "RACI Matrix",
            "Acceptance Criteria Definition",
            "Requirements Sign-off & Approval",
        ],
    },
    {
        "engagement_type": "Organizational Change",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Survey & Questionnaire Design",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Gap Analysis",
            "Future State Design",
            "Process Modeling — Future State",
            "Change Strategy Definition",
            "RACI Matrix",
            "Performance Metrics Definition",
            "Requirements Prioritization",
            "Requirements Sign-off & Approval",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── New Product / Service Development ───────────────────────────────────
    # Sequencing rationale:
    #   Problem Statement and Business Need before stakeholder engagement.
    #   Elicitation Planning before conducting elicitation.
    #   User Stories after business/functional requirements are established.
    #   Prototyping after requirements, before acceptance criteria.
    {
        "engagement_type": "New Product / Service Development",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Interviews",
            "Functional Requirements Documentation",
            "User Story Writing",
            "Acceptance Criteria Definition",
        ],
    },
    {
        "engagement_type": "New Product / Service Development",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Elicitation Planning",
            "Stakeholder Interviews",
            "Document Analysis",
            "Current State Assessment",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Business Rules Documentation",
            "User Story Writing",
            "Solution Prototyping & Wireframing",
            "Acceptance Criteria Definition",
            "Requirements Prioritization",
            "Requirements Sign-off & Approval",
            "UAT Planning & Support",
        ],
    },
    {
        "engagement_type": "New Product / Service Development",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Benchmarking & Market Analysis",
            "Current State Assessment",
            "Elicitation Planning",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Survey & Questionnaire Design",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Data Requirements Definition",
            "Business Rules Documentation",
            "User Story Writing",
            "Use Case Development",
            "Solution Prototyping & Wireframing",
            "Acceptance Criteria Definition",
            "Requirements Verification",
            "Requirements Validation",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "Change Strategy Definition",
            "UAT Planning & Support",
            "Solution Performance Assessment",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Vendor Selection & Procurement ──────────────────────────────────────
    # Sequencing rationale:
    #   Stakeholder Interviews before Benchmarking — understand internal needs
    #   before researching the market.
    #   Assumptions & Constraints early — procurement constraints are upfront.
    #   Risk Assessment informs requirements prioritization.
    #   Sign-off last.
    {
        "engagement_type": "Vendor Selection & Procurement",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Stakeholder Interviews",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
        ],
    },
    {
        "engagement_type": "Vendor Selection & Procurement",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Interviews",
            "Assumption & Constraint Documentation",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Business Rules Documentation",
            "Risk Assessment",
            "Requirements Prioritization",
            "Requirements Sign-off & Approval",
        ],
    },
    {
        "engagement_type": "Vendor Selection & Procurement",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Current State Assessment",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Elicitation Results Documentation",
            "Risk Assessment",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Non-Functional Requirements Documentation",
            "Business Rules Documentation",
            "Requirements Prioritization",
            "Requirements Verification",
            "Requirements Baselining",
            "Requirements Sign-off & Approval",
            "Solution Performance Assessment",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },

    # ─── Strategic Initiative ─────────────────────────────────────────────────
    # Sequencing rationale:
    #   Document Analysis and Stakeholder Interviews before Current State Assessment
    #   — gather external/internal context before synthesising the current state.
    #   Assumptions & Constraints after initial elicitation.
    #   Root Cause Analysis and Risk Assessment before defining future state.
    #   Gap Analysis bridges current/future state analysis.
    #   Business Case Development after understanding gaps and future state.
    {
        "engagement_type": "Strategic Initiative",
        "scale_tier": "Request",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Stakeholder Interviews",
            "Document Analysis",
            "Business Case Development",
        ],
    },
    {
        "engagement_type": "Strategic Initiative",
        "scale_tier": "Engagement",
        "module_sequence": [
            "Problem Statement Definition",
            "Business Need Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Document Analysis",
            "Benchmarking & Market Analysis",
            "Assumption & Constraint Documentation",
            "Current State Assessment",
            "Root Cause Analysis",
            "Risk Assessment",
            "Gap Analysis",
            "Future State Design",
            "Change Strategy Definition",
            "Business Case Development",
            "Requirements Sign-off & Approval",
        ],
    },
    {
        "engagement_type": "Strategic Initiative",
        "scale_tier": "Initiative",
        "module_sequence": [
            "BA Approach Definition",
            "Stakeholder Register",
            "Stakeholder Engagement Planning",
            "BA Governance Setup",
            "Information Management Planning",
            "Performance Metrics Definition",
            "Problem Statement Definition",
            "Business Need Definition",
            "Assumption & Constraint Documentation",
            "Current State Assessment",
            "Process Modeling — Current State",
            "Stakeholder Interviews",
            "Workshops & Focus Groups",
            "Survey & Questionnaire Design",
            "Benchmarking & Market Analysis",
            "Elicitation Results Documentation",
            "Root Cause Analysis",
            "Risk Assessment",
            "Gap Analysis",
            "Future State Design",
            "Process Modeling — Future State",
            "Change Strategy Definition",
            "Business Requirements Documentation",
            "Functional Requirements Documentation",
            "Business Case Development",
            "Requirements Prioritization",
            "Requirements Traceability Setup",
            "Traceability Matrix",
            "Requirements Sign-off & Approval",
            "Value Delivery Assessment",
            "Post-Implementation Review",
            "Lessons Learned Documentation",
        ],
    },
]
